name: Deploy Frontend to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'   # 👈 staying on Node 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Copy everything needed for runtime into /build
      - name: Prepare build artifacts
        run: |
          mkdir build
          cp -r .next node_modules public package*.json next.config.* build/ || true

      # Prevent Azure from rebuilding (forces it to just run our bundle)
      - name: Disable Oryx build
        run: |
          echo '[config]' > build/.deployment
          echo 'SCM_DO_BUILD_DURING_DEPLOYMENT=false' >> build/.deployment

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: NP-FE
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build
